CREATE TABLE users
(
id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
email VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
user_role INT UNSIGNED NOT NULL,
UNIQUE(email,PASSWORD,user_role),
FOREIGN KEY (user_role) REFERENCES user_role(id)
);